let g:winManagerWindowLayout='FileExplorer|TagList'
nmap wm :WMToggle<cr>
filetype plugin indent on
set completeopt=longest,menu
let Tlist_Ctags_Cmd = '/usr/local/bin/ctags'
colorscheme desert
set nu
set autochdir
" 开启语法高亮
syntax enable
syntax on
" 显示或者隐藏NERDTree
map <F10> :NERDTreeToggle<CR>
set encoding=utf-8
" 设置文字编码自动识别
set fencs=utf-8,gb2312
" 高亮光标所在行
set cul
" 设置字典~/.vim/dict/javascript.dict是字典文件的路径
" autocmd FileType javascript set dictionary=~/.vim/dict/javascript.dict.txt
" 打开javascript折叠
" let b:javascript_fold=1
" 打开javascript对dom,html,css的支持
" let javascript_enable_domhtmlcss=1
" emmet在vim中启用
let g:user_emmet_mode='n'
let g:user_emmet_mode='inv'
let g:user_emmet_mode='a'
" emmet只对html/css启用
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall
let g:user_emmet_expandabbr_key = '<c-e>'
" 手动折叠
set foldmethod=manual
" 显示中文帮助
if version >=603
	set helplang=cn
	set encoding=utf-8
endif
" 设置背景主题
color desert
" 使用鼠标
set mouse=a
" 设置高亮搜索
set hlsearch
" 输入字符串就显示匹配点
set incsearch
" 输入的命令显示出来，看的清楚些。
set showcmd
" Tlist的内部变量。函数列表。
" 窗口在右边显示
" let Tlist_Use_Right_Window=1
let Tlist_File_Fold_Auto_Close=1
" 自动保存
set autowrite
" 禁止生成临时文件
set nobackup
" autocmd VimEnter * NERDTree
" 代码补全
set completeopt=preview,menu
" 允许插件
filetype plugin on 
" 当打开NERDTree窗口时,自动显示Bookmarks
let NERDTreeShowBookmarks=1
" 打开当前目录文件列表
map <F3> :Explore<CR>
" 函数和变量列表
" map <F4> :TlistToggle<CR>
" 搜索当前词，并打开quickfix窗口
map <F5> :call Search_Word()<CR>
" 全能补全
" inoremap <F8> <C-x><C-o>
" 没事，鼠标画线玩的。
" noremap <F9> :call ToggleSketch()<CR>
" 启动函数变量快速浏览的时间设置
set updatetime=100
if has("cscope")
set csprg=/usr/bin/cscope
set csto=0
set cst
set nocsverb
" add any database in current directory
if filereadable("cscope.out")
cs add cscope.out
" else add database pointed to by environment
elseif $CSCOPE_DB != ""
cs add $CSCOPE_DB
endif
" 语言设置
set langmenu=zh_CN.UTF-8
" 带有如下符号的单词不要被换行分割
set iskeyword+=_,$,@,%,#,-
set csverb
set cscopetag
set cscopequickfix=s-,g-,c-,d-,t-,e-,f-,i-
endif
nnoremap <silent> <F8> :TlistToggle<CR>
set autoindent "自动缩进
set smartindent "智能缩进
set cindent "C缩进
set completeopt=longest,menu
set tabstop=4
set softtabstop=4
set shiftwidth=4
set showmatch
set tags=tags;
set autochdir
set nocompatible
set backspace=2
nnoremap <silent> <F2> :A<CR>
